/**
 * First-run seed data.
 *
 * CREW is useless as an empty shell, so a first open builds a realistic PSA
 * two-day pairing anchored to today plus a short sample logbook. Everything
 * seeded is marked as sample and can be cleared from Settings in one tap.
 */

import { findAirport } from '../data/airportIndex';
import { dateKeyIn, instantFromLocal, shiftDateKey } from '../core/time/time';
import type { DutyDay, FlightRecord, Leg, Tail, Trip } from '../core/types';

let seq = 0;
const id = (p: string) => `${p}-seed-${(seq++).toString(36)}`;

interface LegSpec {
  flight: string;
  from: string;
  to: string;
  dep: string;
  arr: string;
  tail?: string;
  aircraftId?: string;
}

function buildLeg(dateKey: string, spec: LegSpec): Leg {
  const fromTz = findAirport(spec.from)?.tz ?? 'UTC';
  const toTz = findAirport(spec.to)?.tz ?? 'UTC';
  const dep = instantFromLocal(dateKey, spec.dep, fromTz);
  let arr = instantFromLocal(dateKey, spec.arr, toTz);
  if (dep && arr && arr.getTime() < dep.getTime()) {
    arr = instantFromLocal(shiftDateKey(dateKey, 1), spec.arr, toTz);
  }
  return {
    id: id('leg'),
    kind: 'flight',
    flightNumber: spec.flight,
    from: spec.from,
    to: spec.to,
    depart: dep ? dep.toISOString() : null,
    arrive: arr ? arr.toISOString() : null,
    aircraftId: spec.aircraftId ?? 'crj700',
    tail: spec.tail ?? null,
    blockMinutes: dep && arr ? Math.round((arr.getTime() - dep.getTime()) / 60000) : null,
  };
}

/**
 * A two-day DAY-based pairing with a Charlotte overnight, anchored to today
 * so the context engine always has something real to reason about.
 */
export function buildSampleTrip(now = new Date()): Trip {
  const homeTz = findAirport('KDAY')?.tz ?? 'America/New_York';
  const day1 = dateKeyIn(now, homeTz) ?? '2026-01-01';
  const day2 = shiftDateKey(day1, 1);

  const d1Legs: LegSpec[] = [
    { flight: '5142', from: 'KDAY', to: 'KCLT', dep: '06:00', arr: '07:21', tail: 'N705PS' },
    { flight: '5388', from: 'KCLT', to: 'KDCA', dep: '08:15', arr: '09:32', tail: 'N705PS' },
    { flight: '5401', from: 'KDCA', to: 'KCLT', dep: '10:25', arr: '11:56', tail: 'N705PS' },
  ];
  const d2Legs: LegSpec[] = [
    { flight: '5217', from: 'KCLT', to: 'KRIC', dep: '06:35', arr: '07:44', tail: 'N713PS', aircraftId: 'crj900' },
    { flight: '5230', from: 'KRIC', to: 'KCLT', dep: '08:30', arr: '09:52', tail: 'N713PS', aircraftId: 'crj900' },
    { flight: '5119', from: 'KCLT', to: 'KDAY', dep: '11:05', arr: '12:31', tail: 'N713PS', aircraftId: 'crj900' },
  ];

  const mk = (dateKey: string, specs: LegSpec[], report: string, release: string, tz: string, hotel: DutyDay['hotel']): DutyDay => ({
    id: id('day'),
    date: dateKey,
    reportAt: instantFromLocal(dateKey, report, tz)?.toISOString() ?? null,
    releaseAt: instantFromLocal(dateKey, release, tz)?.toISOString() ?? null,
    legs: specs.map((s) => buildLeg(dateKey, s)),
    hotel,
  });

  return {
    id: id('trip'),
    number: '4412',
    days: [
      mk(day1, d1Legs, '05:15', '12:11', homeTz, {
        name: 'Crew hotel — Charlotte (set yours in the trip editor)',
        transitMinutes: 20,
      }),
      mk(day2, d2Legs, '05:50', '12:46', findAirport('KCLT')?.tz ?? 'America/New_York', null),
    ],
    creditMinutes: null,
    perDiemRate: null,
    notes: 'Sample pairing generated by CREW so the app has something to reason about. Replace it with your own via Make Sense Of This.',
  };
}

export function buildSampleTails(): Tail[] {
  return [
    { registration: 'N705PS', aircraftId: 'crj700', operator: 'PSA Airlines', flightCount: 14 },
    { registration: 'N713PS', aircraftId: 'crj900', operator: 'PSA Airlines', flightCount: 9 },
    { registration: 'N556NN', aircraftId: 'crj900', operator: 'PSA Airlines', flightCount: 3 },
  ];
}

/** A short sample logbook so the statistics and fleet screens are alive. */
export function buildSampleFlights(now = new Date()): FlightRecord[] {
  const routes: [string, string, number, string, string][] = [
    ['KDAY', 'KCLT', 81, 'crj700', 'N705PS'],
    ['KCLT', 'KDCA', 77, 'crj700', 'N705PS'],
    ['KDCA', 'KCLT', 91, 'crj700', 'N705PS'],
    ['KCLT', 'KPHL', 96, 'crj900', 'N713PS'],
    ['KPHL', 'KCLT', 104, 'crj900', 'N713PS'],
    ['KCLT', 'KORF', 72, 'crj700', 'N705PS'],
    ['KORF', 'KCLT', 78, 'crj700', 'N705PS'],
    ['KCLT', 'KTYS', 58, 'crj700', 'N556NN'],
    ['KTYS', 'KCLT', 61, 'crj700', 'N556NN'],
    ['KCLT', 'KSAV', 68, 'crj900', 'N713PS'],
    ['KSAV', 'KCLT', 74, 'crj900', 'N713PS'],
    ['KCLT', 'KDAY', 86, 'crj700', 'N705PS'],
  ];
  const base = dateKeyIn(now, 'America/New_York') ?? '2026-01-01';
  return routes.map((r, i) => ({
    id: id('flt'),
    date: shiftDateKey(base, -(30 - i * 2)),
    from: r[0],
    to: r[1],
    blockMinutes: r[2],
    aircraftId: r[3],
    tail: r[4],
    seat: 'FO' as const,
    sample: true,
  }));
}
