/**
 * Generates the service worker after a build.
 *
 * The worker precaches the built app shell so CREW opens instantly and works
 * with no signal — which is most of a hotel and all of a jetway. External
 * data (weather) is never cached here; the fetch layer handles that itself so
 * stale data always carries its own "cached at" label.
 */

import { readdirSync, statSync, writeFileSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const DIST = 'dist';
const BASE = '/CREW/';

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

const files = walk(DIST)
  .map((f) => relative(DIST, f).split('\\').join('/'))
  // The worker caches itself implicitly, and dotfiles (.nojekyll) are build
  // plumbing that a host need not serve — asking for one that 404s would
  // abort the whole install.
  .filter((f) => f !== 'sw.js' && !f.split('/').some((part) => part.startsWith('.')))
  .map((f) => BASE + f);

// A hash of the asset list so every deploy invalidates the old cache.
const version = readFileSync(join(DIST, 'index.html'), 'utf8').length + '-' + files.length;

const sw = `/* Generated by scripts/gen-sw.mjs — do not edit by hand. */
const CACHE = 'crew-v${version}';
const ASSETS = ${JSON.stringify([...files, BASE], null, 2)};

self.addEventListener('install', (event) => {
  // Cache entries individually: addAll rejects the whole install if any one
  // request fails, which would leave the app with no offline support at all.
  event.waitUntil(
    caches.open(CACHE)
      .then((c) => Promise.allSettled(ASSETS.map((url) => c.add(url))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  // Only ever serve our own origin from the cache. Weather and other external
  // data go straight to the network so the app never shows silently old
  // readings without the fetch layer knowing about it.
  if (url.origin !== self.location.origin) return;

  // Navigations: fall back to the cached shell so a cold launch works offline.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req).catch(() => caches.match('${BASE}index.html').then((r) => r || caches.match('${BASE}')))
    );
    return;
  }

  event.respondWith(
    caches.match(req).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
      }
      return res;
    }))
  );
});
`;

writeFileSync(join(DIST, 'sw.js'), sw);
// GitHub Pages runs Jekyll by default, which drops files starting with _.
writeFileSync(join(DIST, '.nojekyll'), '');
console.log(`sw.js written — ${files.length} assets precached`);
